interface Estudiante {
  nombre: string;
  ru: string;
  paralelo: string;
  asistencia: number;
  practicas: number;
  practicaOp: number;
  extra: number;
  acumulado: number;
  notaTotal: number;
}

const estudiantesAuxiliarB: Estudiante[] = [
  { nombre: "CALLE YESICA ADRIANA", ru: "200072738", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHIPANA EDWIN JHONNY", ru: "200026839", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ADUVIRI BAUTISTA HUGO", ru: "200072840", paralelo: "B", asistencia: 4, practicas: 0, practicaOp: 1, extra: 0, acumulado: 5, notaTotal: 5 },
  { nombre: "AJACOPA LAURA DAMARIS", ru: "200068952", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ajno huchani jhonny", ru: "200063606", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ALAVE TOLA ANAHI BELEN", ru: "200075561", paralelo: "B", asistencia: 3, practicas: 2, practicaOp: 1, extra: 0, acumulado: 6, notaTotal: 6 },
  { nombre: "ALAVI OSCORI DEYSI ELIZABETH", ru: "200076971", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ALMANZA LOPEZ JHEISON", ru: "200030924", paralelo: "B", asistencia: 2, practicas: 1, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "AMARU MAMANI CRISTHIAN REYNALDO", ru: "200026614", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "APAZA APAZA IVAN BISMARCK", ru: "200075735", paralelo: "B", asistencia: 1, practicas: 0, practicaOp: 0, extra: 0, acumulado: 1, notaTotal: 1 },
  { nombre: "apaza perez maria isabel", ru: "200072861", paralelo: "B", asistencia: 1, practicas: 0, practicaOp: 0, extra: 0, acumulado: 1, notaTotal: 1 },
  { nombre: "APAZA TITERICO ROGER", ru: "200063828", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "APAZA VILLA CARLA", ru: "200075585", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 1, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "Aquise Morales Alan Robert", ru: "200059931", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ARRATIA ALEJO ARIEL JIMMY", ru: "200038570", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "AVENDAÑO CASTRO ISSAC MOISES", ru: "200029207", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CACHI FLORES BRAYAN", ru: "200076984", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "Callata Acarapi Jhonatan Stip", ru: "200075578", paralelo: "B", asistencia: 5, practicas: 3, practicaOp: 2, extra: 1, acumulado: 11, notaTotal: 10 },
  { nombre: "Calle Mayta Cristian Alex", ru: "200075583", paralelo: "B", asistencia: 5, practicas: 2, practicaOp: 1, extra: 0, acumulado: 8, notaTotal: 8 },
  { nombre: "CALLISAYA MAMANI ROGER", ru: "200072903", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CAPARICONA AVILE ALEJANDRO", ru: "200077112", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHAMBI MAMANI ESMERALDA GRACE", ru: "200075733", paralelo: "B", asistencia: 1, practicas: 0, practicaOp: 0, extra: 0, acumulado: 1, notaTotal: 1 },
  { nombre: "Chambi Quispe Laura", ru: "200075545", paralelo: "B", asistencia: 7, practicas: 3, practicaOp: 1, extra: 1, acumulado: 12, notaTotal: 10 },
  { nombre: "CHINO GUACHALLA DANIEL", ru: "200075626", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 1, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "CHIPANA CHAMBI ERICK EDDY", ru: "200075628", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHOQUE AYCA FRANKLIN", ru: "14007268", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "CHOQUE HUANCA KEVIN BEYMAR", ru: "200075887", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 1, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "CHOQUE RONDO JOSE", ru: "200075630", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHOQUETARQUI GOMEZ ELSA", ru: "200047631", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHOQUETARQUI JANCO YUCY DAYANA", ru: "200032193", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 1, acumulado: 1, notaTotal: 1 },
  { nombre: "Chuquimia Villazante Kevin", ru: "200075632", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Chura Mamani Sergio Raul", ru: "200075634", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHURA SALAS YESSICA YESENIA", ru: "200072922", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CLEMENTE CALATURO EVER", ru: "200063706", paralelo: "B", asistencia: 6, practicas: 2, practicaOp: 1, extra: 0, acumulado: 9, notaTotal: 9 },
  { nombre: "COLQUE ARGANI YECID JHOEL", ru: "200065288", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CONDORI CHOQUEVILLCA BRAYAN", ru: "200076941", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 1, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "COPA YUJRA FRANKLIN", ru: "200075593", paralelo: "B", asistencia: 6, practicas: 3, practicaOp: 0, extra: 0, acumulado: 9, notaTotal: 9 },
  { nombre: "CORINA CHOQUE ALEX FRANZ", ru: "200075758", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "Enriquez Villca Juan Belen", ru: "200072935", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ESPINOZA TICONA NELIDA", ru: "200075695", paralelo: "B", asistencia: 5, practicas: 2, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "FERNANDEZ ARANDA RODRIGO", ru: "200075694", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Fernandez Quispe Fernando Jamil", ru: "200077142", paralelo: "B", asistencia: 2, practicas: 1, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "FLORES APAZA MIGUEL ANGEL", ru: "200076926", paralelo: "B", asistencia: 4, practicas: 3, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "FLORES MOLLO JULIA", ru: "200079402", paralelo: "B", asistencia: 5, practicas: 3, practicaOp: 0, extra: 0, acumulado: 8, notaTotal: 8 },
  { nombre: "FLORES TICONA JOSUE DARIO", ru: "200065285", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "GARCIA LIUCA GLADYS", ru: "200017198", paralelo: "B", asistencia: 5, practicas: 2, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "GUTIERREZ QUISPE EFRAIN", ru: "200065319", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "HUANCA APAZA MIGUEL ANGEL", ru: "200050955", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Huanca Cari Victor Emanuel", ru: "200075687", paralelo: "B", asistencia: 2, practicas: 2, practicaOp: 0, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "HUANCA SANGA JORGE GUSTAVO", ru: "200065599", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "HUANCA VELASCO KEVIN ANGELO", ru: "200075681", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "HUITO ADUVIRI ANA ISABEL", ru: "200075680", paralelo: "B", asistencia: 5, practicas: 2, practicaOp: 1, extra: 0, acumulado: 8, notaTotal: 8 },
  { nombre: "Kantuta Copa Ruben Angel", ru: "200075679", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "LARUTA QUINO JHONATAN RODRIGO", ru: "200075678", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 1, acumulado: 1, notaTotal: 1 },
  { nombre: "LAURA LOPEZ JHON KEVIN", ru: "200076943", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "LECOÑA HUAYHUA JOSE DAVID", ru: "200065373", paralelo: "B", asistencia: 6, practicas: 2, practicaOp: 1, extra: 1, acumulado: 10, notaTotal: 10 },
  { nombre: "LECOÑA QUISPE ANABEL MELANIE", ru: "200076946", paralelo: "B", asistencia: 4, practicas: 3, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "ledezma garcia jose armando", ru: "200063757", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "LIMACHI QUISPE LIMBER", ru: "200050701", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 1, extra: 0, acumulado: 1, notaTotal: 1 },
  { nombre: "LLUSCO MAMANI HERICA", ru: "200050879", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "LUNA SANTOS BORIS YERKO", ru: "200080114", paralelo: "B", asistencia: 7, practicas: 2, practicaOp: 1, extra: 0, acumulado: 10, notaTotal: 10 },
  { nombre: "MACHACA CAPIA MIGUEL", ru: "200075793", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI KUNO DINA", ru: "200079397", paralelo: "B", asistencia: 5, practicas: 1, practicaOp: 1, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "MAMANI MAMANI RODRIGO JHONATAN", ru: "200076955", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 1, acumulado: 1, notaTotal: 1 },
  { nombre: "Mamani Mollinedo Helen Keilly", ru: "200075664", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 1, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "mamani mollinedo kevin", ru: "200063733", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI PERCA HEBERT", ru: "200075760", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "masco quispe maria belen", ru: "200075657", paralelo: "B", asistencia: 5, practicas: 3, practicaOp: 1, extra: 1, acumulado: 10, notaTotal: 10 },
  { nombre: "MATIAS CHOQUE ALEXANDRA YLEN", ru: "200063578", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAYTA MAMANI HERNAN", ru: "200075656", paralelo: "B", asistencia: 5, practicas: 0, practicaOp: 0, extra: 0, acumulado: 5, notaTotal: 5 },
  { nombre: "MORENO SALAZAR SERGIO GUSTAVO", ru: "200075652", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 1, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "NACHO HUANCA JUAN CARLOS", ru: "200017188", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "NINA CHOQUE MILTON", ru: "200076963", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "NINA LIMACHI IVAN OMAR", ru: "200047853", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "PACHANI MAMANI DAISY", ru: "200075649", paralelo: "B", asistencia: 3, practicas: 2, practicaOp: 0, extra: 0, acumulado: 5, notaTotal: 5 },
  { nombre: "PACHARI RODRIGUEZ CARLOS MANUEL", ru: "200080743", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 1, extra: 1, acumulado: 4, notaTotal: 4 },
  { nombre: "Paco Mamani Alejandro Tomas", ru: "200075648", paralelo: "B", asistencia: 2, practicas: 1, practicaOp: 1, extra: 1, acumulado: 5, notaTotal: 5 },
  { nombre: "PACO SUMI RONALD", ru: "200072733", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "PACORICONA LIMACHI IVAN RODRIGO", ru: "200076959", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "PANIAGUA TICONA ALEJANDRA VALENTINA", ru: "200063595", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "PILCO SALINAS JUAN GABRIEL", ru: "200019413", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "Pinto Cutili Joel Freddy", ru: "200075740", paralelo: "B", asistencia: 1, practicas: 0, practicaOp: 1, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "POMA MARCA ROBERTO CARLOS", ru: "200075644", paralelo: "B", asistencia: 2, practicas: 2, practicaOp: 1, extra: 0, acumulado: 5, notaTotal: 5 },
  { nombre: "PORCEL APAZA CLARIBEL REYNA", ru: "200072869", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "PUCHO CASTILLO LUIS ANTONIO", ru: "200047831", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "PUCHO POOL ARACELY BELEN", ru: "200075643", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUENTA LARA JOEL LUIS", ru: "200019261", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUISPE ANCASI EMANUEL CRISTOPHER", ru: "200072876", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUISPE CHOQUE OMAR FERNANDO", ru: "200050619", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUISPE GUAYGUA IRENE", ru: "200075640", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 1, extra: 0, acumulado: 1, notaTotal: 1 },
  { nombre: "QUISPE QUISPE BRAYAN", ru: "200072885", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "RAMOS TICONA ALVARO ERICK", ru: "200029503", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "SACACA MAMANI ALEX GONZALO", ru: "200015570", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "SIRPA VALENCIA MIGUEL ANGEL", ru: "200075705", paralelo: "B", asistencia: 1, practicas: 0, practicaOp: 1, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "TANCARA QUISPE ANDREA DAYANA", ru: "200076935", paralelo: "B", asistencia: 7, practicas: 3, practicaOp: 1, extra: 0, acumulado: 11, notaTotal: 10 },
  { nombre: "TICONA QUISPE MELANY  AIDEE", ru: "200076937", paralelo: "B", asistencia: 3, practicas: 3, practicaOp: 0, extra: 0, acumulado: 6, notaTotal: 6 },
  { nombre: "TICONIPA CALLE JHONNY", ru: "200063581", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "TINTAYA QUISPE ANGELA ADRIANA", ru: "200075710", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 1, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "TONCONI VALENCIA MARCOS FERNANDO", ru: "200075714", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Torrez Herrera Brandon Gustavo", ru: "200050656", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "torrez patty guillermo luis", ru: "200075715", paralelo: "B", asistencia: 3, practicas: 0, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "Troche Mamani Alexander", ru: "200076940", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 1, extra: 1, acumulado: 4, notaTotal: 4 },
  { nombre: "TUPA GUTIERREZ NILDA ERIKA", ru: "200075716", paralelo: "B", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "VERA CHOQUEHUANCA MARIA JOSE", ru: "200079399", paralelo: "B", asistencia: 7, practicas: 2, practicaOp: 1, extra: 1, acumulado: 11, notaTotal: 10 },
  { nombre: "yana calderon franco alex", ru: "200075719", paralelo: "B", asistencia: 5, practicas: 0, practicaOp: 1, extra: 0, acumulado: 6, notaTotal: 6 },
  { nombre: "Yana Quisbert Vania Paola", ru: "200075720", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "YUJRA QUENTA DANA KATE", ru: "200080604", paralelo: "B", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 }
];

const estudiantesAuxiliarC: Estudiante[] = [
  { nombre: "ACARAPI PARI CALEB ANDRES", ru: "200077473", paralelo: "C", asistencia: 7, practicas: 5, practicaOp: 0, extra: 1, acumulado: 13, notaTotal: 10 },
  { nombre: "ACHACOLLO VALERIANO CRISTIAN ADHEMAR", ru: "200076966", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "AGUILAR YANA PAOLA", ru: "200036403", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ALBORTA GONZALES MARCO ANTONIO", ru: "200072728", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "ALIAGA CHIPANA JOSE MANUEL", ru: "200072846", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ALLCA QUISPE ROGER ROLANDO", ru: "14005171", paralelo: "C", asistencia: 7, practicas: 1, practicaOp: 0, extra: 0, acumulado: 8, notaTotal: 8 },
  { nombre: "Almaraz Mendoza John Luis", ru: "200075737", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ALVARADO QUISPE MARCO ANTONIO", ru: "200047748", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "ARELLANO APAZA LUIS MIGUEL", ru: "200029391", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ARRATIA ALEJO ALEXANDER JAVIER", ru: "200038571", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "ARUNI PAYE ROSMERY", ru: "200075568", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "BEDOYA HUAYHUA HALBIN ANDY", ru: "200047639", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CALLE MAYTA VIDAL JAIME", ru: "200075581", paralelo: "C", asistencia: 7, practicas: 1, practicaOp: 0, extra: 1, acumulado: 9, notaTotal: 9 },
  { nombre: "CANAVIRI CHURA DIANA", ru: "200021919", paralelo: "C", asistencia: 3, practicas: 1, practicaOp: 1, extra: 0, acumulado: 5, notaTotal: 5 },
  { nombre: "CARI PACO BETHY MERCEDES", ru: "200075590", paralelo: "C", asistencia: 7, practicas: 3, practicaOp: 0, extra: 0, acumulado: 10, notaTotal: 10 },
  { nombre: "CASA APAZA OSTIN GABRIEL", ru: "200075616", paralelo: "C", asistencia: 4, practicas: 0, practicaOp: 0, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "Casas Churqui Jesse", ru: "200076991", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CASTRO AJHUACHO SAMIRA", ru: "200073262", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "Chacolla Ramos Erick kevin", ru: "200059871", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHAMBI QUISPE IVONE NAYDELIN", ru: "200079501", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "CHOQUE CONDORI ABIGAIL FELIPA", ru: "200065243", paralelo: "C", asistencia: 4, practicas: 0, practicaOp: 0, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "CHOQUE MAMANI GABRIELA ALEJANDRA", ru: "200003372", paralelo: "C", asistencia: 7, practicas: 4, practicaOp: 1.5, extra: 0, acumulado: 13, notaTotal: 10 },
  { nombre: "CHOQUE PERALTA FERNANDO", ru: "200076997", paralelo: "C", asistencia: 7, practicas: 2, practicaOp: 0, extra: 0, acumulado: 9, notaTotal: 9 },
  { nombre: "CHOQUE QUISPE JAVIER JOSE", ru: "200077000", paralelo: "C", asistencia: 7, practicas: 5, practicaOp: 0, extra: 1, acumulado: 13, notaTotal: 10 },
  { nombre: "CHOQUE SIRPA ALEXANDER", ru: "200077002", paralelo: "C", asistencia: 7, practicas: 5, practicaOp: 1, extra: 0, acumulado: 13, notaTotal: 10 },
  { nombre: "CHUNGARA CHUNGARA ANA KAORI", ru: "200012127", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CHURA QUISPE WILSON RENE", ru: "200075635", paralelo: "C", asistencia: 7, practicas: 3, practicaOp: 0, extra: 0, acumulado: 10, notaTotal: 10 },
  { nombre: "COAQUIRA ALANOCA MICHAEL DOUGLAS", ru: "200072923", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "COCA GIRONDA EDGAR CHRISTIAN", ru: "200075573", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "CONDE QUISPE ERIKA", ru: "200072924", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CONDORI CHAMBI DAYSI", ru: "200065568", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CONDORI CUENCA JAVIER", ru: "15008956", paralelo: "C", asistencia: 0, practicas: 1.5, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "condori PAYI JUAN FRANCISCO", ru: "200065227", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "Condori Salle Alex Juan", ru: "200075592", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CORNEJO PATTY TITO GONZALO", ru: "8000803", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "coronel conde ariel joel", ru: "200075611", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "CRUZ ALCON JOSE ANTONIO", ru: "13001347", paralelo: "C", asistencia: 4, practicas: 2, practicaOp: 0, extra: 0, acumulado: 6, notaTotal: 6 },
  { nombre: "Cutili Condori Niver", ru: "200076922", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "DE LA CRUZ CABRERA JAQUELINE", ru: "200072931", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "DIAZ MAMANI DANY WINSOR", ru: "200075613", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "DURAN SULLCAMANI CARLOS", ru: "200036363", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "ESPINOZA HUANCA JOSE LUIS", ru: "200075615", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "FLORES AYALA LUZ BELEN", ru: "200079410", paralelo: "C", asistencia: 7, practicas: 1, practicaOp: 0, extra: 0, acumulado: 8, notaTotal: 8 },
  { nombre: "Gutierrez Choquehuanca Ednovi Yhosiney", ru: "200077143", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "HERRERA CARPIO RUDY", ru: "200066927", paralelo: "C", asistencia: 3, practicas: 0, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "HUANCA QUISPE WILLIAMS GERMAN", ru: "200075756", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "HUAYHUA PACHACUTI RICHARD", ru: "200036378", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "HUAYHUA YUJRA ELIAS", ru: "11001278", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "LAIME CARVAJAL JOSE LUIS", ru: "200050868", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "LAIME CRUZ EMANUEL", ru: "200059693", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Laura De La Cruz Yessenia abigail", ru: "200076939", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "LIMACHI RENJIFO DAYED", ru: "200047731", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "LIMACHI SURCO FERNANDO RUSSELL", ru: "200076950", paralelo: "C", asistencia: 7, practicas: 3, practicaOp: 0, extra: 0, acumulado: 10, notaTotal: 10 },
  { nombre: "LLUTA ALI ALICIA GABRIELA", ru: "200026706", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MACHICADO CALCINA HENRY RAUL", ru: "200060098", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI ANCALLA ANA LIZ", ru: "200026762", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI APAZA WILMAR", ru: "200050886", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI CHOQUE RENAN DIEGO", ru: "15000127", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI CHURA JUDITH", ru: "200038440", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "MAMANI CONDORI RODOLFO", ru: "200075671", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "MAMANI GUTIERREZ ZIBEON", ru: "200020630", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "MAMANI MAMANI EVER SALVADOR", ru: "15009104", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI MARQUEZ PAMELA", ru: "200075666", paralelo: "C", asistencia: 7, practicas: 1, practicaOp: 0, extra: 0, acumulado: 8, notaTotal: 8 },
  { nombre: "MAMANI MAYTA YOLISA", ru: "200075665", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "MAMANI PERALTA DANIELA ROCIO", ru: "15006398", paralelo: "C", asistencia: 7, practicas: 2, practicaOp: 0, extra: 0, acumulado: 9, notaTotal: 9 },
  { nombre: "mamani poma angel", ru: "200059690", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI QUELCA ELOY", ru: "200038359", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI RAMIREZ FABIAN", ru: "20025839", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI SALLUCA MIGUEL FERNANDO", ru: "200050596", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI SANGA GROVER ABDUL", ru: "200019267", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MAMANI TORREZ ANGHELO", ru: "200063763", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MARCA MAMANI JUAN MIGUEL", ru: "200075658", paralelo: "C", asistencia: 0, practicas: 4, practicaOp: 0, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "MARIÑO PERALTA HEISEL NATALY", ru: "200047794", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MARQUEZ CALLE WILSON", ru: "200065328", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Mendoza Quispe Franklin Vladimir", ru: "200075653", paralelo: "C", asistencia: 7, practicas: 4, practicaOp: 3, extra: 1, acumulado: 15, notaTotal: 10 },
  { nombre: "MOLINA CALLE FREDY", ru: "200059819", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MOLLERICONA QUISPE ROGER CARLOS", ru: "15008986", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MOLLERICONA RAMOS GONZALO", ru: "9001176", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "MURGA CONDORI YOSELIN LIZE", ru: "200076961", paralelo: "C", asistencia: 4, practicas: 0, practicaOp: 0, extra: 0, acumulado: 4, notaTotal: 4 },
  { nombre: "ONOFRE CHIPANA HENRRY BRAYAN", ru: "200077230", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "PARI TICONA ARLYMES NORIE", ru: "200075646", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "PATIÑO ROCABADO DEYDAMIA ZORAYDE", ru: "200050612", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "paye cuellar elizabeth", ru: "200066324", paralelo: "C", asistencia: 5, practicas: 0, practicaOp: 0, extra: 0, acumulado: 5, notaTotal: 5 },
  { nombre: "PILCOMAYO SIÑANI KEVIN FRANKLIN", ru: "200036385", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "POMA HUANCA MIGUEL ANGEL", ru: "200076919", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "POMA MAMANI MARCO ANTONIO", ru: "15000142", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "POMA QUISPE MARVIN FELIX", ru: "200038811", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUISPE BLANCO DANIEL", ru: "200063679", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUISPE CANAVIRI JUDITH NAYDA", ru: "200072775", paralelo: "C", asistencia: 2, practicas: 0, practicaOp: 0, extra: 0, acumulado: 2, notaTotal: 2 },
  { nombre: "QUISPE CAUNA DIEGO", ru: "200017177", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUISPE CHOQUE GUSTAVO VICTOR", ru: "15000076", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "QUISPE CONDORI JHONNY", ru: "200076903", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Quispe Mayta Cecilio Marcos", ru: "200063714", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "RAMIREZ CLAROS JOEL", ru: "200026823", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "RODRIGUEZ POMA WILLIAM KEVIN", ru: "200075702", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "SANGALLI CHUYMA JAIME JERY", ru: "15008826", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "TAMBO AROJA FREDY JAVIER", ru: "200072709", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "TARQUI LIFONSO SELENA", ru: "15000107", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Tarqui Vino Luis Alfredo", ru: "200065444", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "TICONA QUISPE ADRIAN GUALBERTO", ru: "200019326", paralelo: "C", asistencia: 0, practicas: 3, practicaOp: 0, extra: 0, acumulado: 3, notaTotal: 3 },
  { nombre: "TINTAYA GUTIERREZ MAYK ANDRU", ru: "200072895", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "TRIGUERO RONDO MILTON", ru: "200072745", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "TROCHE MAYTA ERICK MARLON", ru: "200029101", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "Varela Alvarado Edwin", ru: "200063718", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "VILA YUJRA LUIS ALFREDO", ru: "200077145", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 },
  { nombre: "YUJRA CORONEL EVER", ru: "200028275", paralelo: "C", asistencia: 7, practicas: 0, practicaOp: 0, extra: 0, acumulado: 7, notaTotal: 7 },
  { nombre: "ZAMBRANA MAMANI JHORDAN", ru: "200076945", paralelo: "C", asistencia: 0, practicas: 0, practicaOp: 0, extra: 0, acumulado: 0, notaTotal: 0 }
];

// Combinar todos los estudiantes en un solo array
const todosLosEstudiantes: Estudiante[] = [
  ...estudiantesAuxiliarB,
  ...estudiantesAuxiliarC
];

export const buscarEstudiante = (codigo: string): Estudiante | null => {
  return todosLosEstudiantes.find((estudiante) => estudiante.ru === codigo) || null;
}

export { estudiantesAuxiliarB, estudiantesAuxiliarC, todosLosEstudiantes, type Estudiante };